name: Build and Test

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: '{{ github.ref }}'
      - uses: actions/setup-dotnet@v1.0.0
        with:
          version: 3.1.100
      - run: |
          cd src
          dotnet build
          dotnet test
           
